station_lst3=['ADARSH NAGAR',
 'AIIMS',
 'AKSHARDHAM',
 'ANAND VIHAR',
 'ARJANGARH',
 'ARTHALA',
 'ASHOK PARK MAIN',
 'ASHRAM',
 'AZADPUR',
 'BADARPUR',
 'BADKAL MOR',
 'BAHADURGARH CITY',
 'BARAKHAMBA ROAD',
 'BATA CHOWK',
 'BHIKAJI CAMA PLACE',
 'BOTANICAL GARDEN',
 'BRIG. HOSHIAR SINGH',
 'CENTRAL SECRETARIAT',
 'CHANDNI CHOWK',
 'CHAWRI BAZAR',
 'CHHATTARPUR',
 'CHIRAG DELHI',
 'CIVIL LINES',
 'DABRI MOR JANAKPURI SOUTH',
 'DASHRATHPURI',
 'DELHI CANTT',
 'DELHI GATE',
 'DILLI HAAT - INA',
 'DILSHAD GARDEN',
 'DURGABAI DESHMUKH SOUTH CAMPUS',
 'DWARKA',
 'DWARKA MOR',
 'DWARKA SEC 10',
 'DWARKA SEC 11',
 'DWARKA SEC 12',
 'DWARKA SEC 13',
 'DWARKA SEC 14',
 'DWARKA SEC 21',
 'DWARKA SEC 8',
 'DWARKA SEC 9',
 'ESCORTS MUJESAR',
 'ESI BASAIDARAPUR',
 'GHEVRA',
 'GHITORNI',
 'GOLF COURSE',
 'GOVIND PURI',
 'GREATER KAILASH',
 'GREEN PARK',
 'GURU DRONACHARYA',
 'GURU TEGH BAHADUR NAGAR',
 'HAIDERPUR BADLI MOR',
 'HARKESH NAGAR OKHLA',
 'HAUZ KHAS',
 'HINDON RIVER',
 'HUDA CITY CENTRE',
 'I.I.T',
 'IFFCO CHOWK',
 'IGD AIRPORT',
 'INDER LOK',
 'INDRAPRASTHA',
 'ITO',
 'JAHANGIRPURI',
 'JAMA MASJID',
 'JAMIA MILLIA ISLAMIA',
 'JANAKPURI EAST',
 'JANAKPURI WEST',
 'JANGPURA',
 'JANPATH',
 'JASOLA APOLLO',
 'JASOLA VIHAR',
 ' SHAHEEN BAGH',
 'JHANDEWALAN',
 'JHILMIL',
 'JLN STADIUM',
 'JORBAGH',
 'KAILASH COLONY',
 'KALINDI KUNJ',
 'KALKAJI MANDIR',
 'KANHAIYA NAGAR',
 'KARKAR DUMA',
 'KAROL BAGH',
 'KASHMERE GATE',
 'KAUSHAMBI',
 'KESHAV PURAM',
 'KHAN MARKET',
 'KIRTI NAGAR',
 'KOHAT ENCLAVE',
 'LAJPAT NAGAR',
 'LAL QUILA',
 'LAXMI NAGAR',
 'LOK KALYAN MARG',
 'M G ROAD',
 'MADI PUR',
 'MAJLIS PARK',
 'MAJOR MOHIT SHARMA RAJENDRA NAGAR',
 'MALVIYA NAGAR',
 'MANDI HOUSE',
 'MANSAROVAR PARK',
 'MAYAPURI',
 'MAYUR VIHAR PKT-1',
 'MAYUR VIHAR-I',
 'MAYUR VIHAR-I EXT',
 'MEWALA MAHARAJPUR',
 'MODEL TOWN',
 'MOHAN ESTATE',
 'MOHAN NAGAR',
 'MOOLCHAND',
 'MOTI NAGAR',
 'MUNDKA',
 'MUNDKA INDUSTRIAL AREA',
 'MUNIRKA',
 'NAJAFGARH',
 'NANGLI',
 'NANGLOI',
 'NANGLOI RLY. STATION',
 'NARAINA VIHAR',
 'NAWADA',
 'NEELAM CHOWK AJRONDA',
 'NEHRU ENCLAVE',
 'NEHRU PLACE',
 'NETAJI SUBHASH PLACE',
 'NEW ASHOK NAGAR',
 'NEW DELHI',
 'NHPC CHOWK',
 'NIRMAN VIHAR',
 'NOIDA CITY CENTRE',
 'NOIDA ELECTRONIC CITY',
 'NOIDA SEC 15',
 'NOIDA SEC 16',
 'NOIDA SEC 18',
 'NSIC OKHLA',
 'OKHLA BIRD SANCTUARY',
 'OKHLA VIHAR',
 'OLD FARIDABAD',
 'PALAM',
 'PANCHSHEEL PARK',
 'PANDIT SHREE RAM SHARMA',
 'PASCHIM VIHAR (EAST)',
 'PASCHIM VIHAR (WEST)',
 'PATEL CHOWK',
 'PATEL NAGAR',
 'PEERA GARHI',
 'PITAM PURA',
 'PRAGATI MAIDAN',
 'PRATAP NAGAR',
 'PREET VIHAR',
 'PUL BANGASH',
 'PUNJABI BAGH',
 'PUNJABI BAGH WEST',
 'QUTAB MINAR',
 'R.K.PURAM',
 'RAJ BAGH',
 'RAJA NAHAR SINGH - BALLABHGARH',
 'RAJDHANI PARK',
 'RAJENDRA PLACE',
 'RAJIV CHOWK',
 'RAJOURI GARDEN',
 'RAMESH NAGAR',
 'RITHALA',
 'RK ASHRAM MARG',
 'ROHINI EAST',
 'ROHINI SECTOR 18,19',
 'ROHINI WEST',
 'SADAR BAZAR',
 'SAKET',
 'SAMAYPUR BADLI',
 'SANT SURDAS',
 'SARAI',
 'SARAI KALE KHAN - NIZAMUDDIN',
 'SARITA VIHAR',
 'SAROJINI NAGAR',
 'SATGURU RAM SINGH MARG',
 'SECTOR - 34 NOIDA',
 'SECTOR - 52 NOIDA',
 'SECTOR - 59 NOIDA',
 'SECTOR - 61 NOIDA',
 'SECTOR - 62 NOIDA',
 'SECTOR-28',
 'SEELAMPUR',
 'SHADIPUR',
 'SHAHDARA',
 'SHAHEED STHAL - NEW BUS ADDA',
 'SHAHID NAGAR',
 'SHAKURPUR',
 'SHALIMAR BAGH',
 'SHANKAR VIHAR',
 'SHASTRI NAGAR',
 'SHASTRI PARK',
 'SHIVAJI PARK',
 'SHYAM PARK',
 'SIKANDARPUR',
 'SIR VISHWESHWARAIAH MOTI BAGH',
 'SOUTH EXTENSION',
 'SUBHASH NAGAR',
 'SUKHDEV VIHAR',
 'SULTANPUR',
 'SURAJMAL STADIUM',
 'TAGORE GARDEN',
 'TIKRI BORDER',
 'TIKRI KALAN',
 'TILAK NAGAR',
 'TIS HAZARI',
 'TUGHLAKABAD',
 'UDYOG BHAWAN',
 'UDYOG NAGAR',
 'UTTAM NAGAR EAST',
 'UTTAM NAGAR WEST',
 'VAISHALI',
 'VASANT VIHAR',
 'VIDHAN SABHA',
 'VINOBAPURI',
 'VISHWAVIDYALAYA',
 'WELCOME',
 'YAMUNA BANK']

#Initializing the Lists
to_lst=[]
from_lst=[]
route_list=[]
fare_lst=[]

#Importing the Necessary Files.
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import os
from tqdm import tqdm_notebook
driver = webdriver.Chrome()
response=driver.get("http://www.delhimetrorail.com/metro-fares.aspx?fs=SAQY8wVbPA8lld&ts=s045vnclU5TvIlld")
for i in tqdm_notebook(range(67,len(station_lst3))):
    for j in tqdm_notebook(range(len(station_lst3))):
        to = driver.find_element_by_id("ctl00_MainContent_ddlFrom")
        fro = driver.find_element_by_id("ctl00_MainContent_ddlTo")
        to.send_keys(station_lst3[i])
        fro.send_keys(station_lst3[j])
        driver.find_element_by_id("ctl00_MainContent_btnShowFare").click()
        route=driver.find_element_by_class_name("fr_stations")
        route2=route.text
        routef=route2.split('\n')
        fare = driver.find_element_by_class_name("fare_new_nor_right")
        faref=fare.text
        fare_lst.append(faref)
        to_lst.append(station_lst3[i])
        from_lst.append(station_lst3[j])
        route_list.append(routef)

#convering Data Into DataFrames and Exporting it.
df=pd.DataFrame({'From':from_lst,'To':to_lst,'Route':route_list,'Fare':fare_lst})
#df.to_json('route_fare11.json')
df.to_csv('Delhi_Metro_Route_Fair.csv',index=False,encoding='utf-8')
df
